from __future__ import annotations

import json
import os
import subprocess
import time
from pathlib import Path
from typing import Any

from metagpt.tools.tool_registry import register_tool

TAGS = ["bi", "dbt", "transformation"]

DEFAULT_DBT_PROJECTS_DIR = Path(__file__).resolve().parent.parent.parent.parent / "dbt_projects"


@register_tool(tags=TAGS)
class DbtRunner:
    """Interact with a dbt Core project: initialise, configure, write models, compile, run, test.

    Each DbtRunner instance is bound to a single dbt project directory after
    init_project() or attach_project() is called.  All subsequent method calls
    operate on that project.

    SQL content for transformation models is generated by the LLM in the ReAct
    reasoning loop and passed to write_model() — this class does NOT generate SQL.
    """

    def __init__(self):
        self._project_dir: Path | None = None

    def _require_project(self) -> Path:
        if self._project_dir is None:
            raise RuntimeError(
                "No dbt project attached. Call init_project() or attach_project() first."
            )
        return self._project_dir

    def _run_dbt(self, *args: str, cwd: Path | None = None) -> dict[str, Any]:
        """Run a dbt CLI command and return stdout/stderr/returncode."""
        target_cwd = str(cwd or self._require_project())
        cmd = ["dbt", *args]
        result = subprocess.run(
            cmd,
            cwd=target_cwd,
            capture_output=True,
            text=True,
        )
        return {
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }

    def init_project(
        self,
        project_name: str,
        project_dir: str | None = None,
        profiles_dir: str | None = None,
    ) -> str:
        """Scaffold a new dbt project using `dbt init`.

        The project is created inside a dedicated `dbt_projects/` folder at the
        repository root (or under `project_dir` if explicitly provided).

        Args:
            project_name: Name of the new dbt project (used as the folder name).
            project_dir: Parent directory to create the project in.
                         Defaults to <repo_root>/dbt_projects/.
            profiles_dir: Directory where profiles.yml will be stored.
                          Defaults to the project directory itself.

        Returns:
            Absolute path of the created project directory.
        """
        parent = Path(project_dir) if project_dir else DEFAULT_DBT_PROJECTS_DIR
        parent.mkdir(parents=True, exist_ok=True)

        target = parent / project_name
        if target.exists():
            self._project_dir = target
            return str(target)

        result = subprocess.run(
            ["dbt", "init", project_name, "--skip-profile-setup"],
            cwd=str(parent),
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(f"dbt init failed:\n{result.stderr}")

        self._project_dir = target
        return str(target)

    def attach_project(self, project_dir: str) -> str:
        """Attach this runner to an already-existing dbt project directory.

        Useful when the project was created in a previous session.

        Args:
            project_dir: Path to the existing dbt project root.

        Returns:
            Absolute path of the project directory.
        """
        path = Path(project_dir)
        if not (path / "dbt_project.yml").exists():
            raise FileNotFoundError(
                f"'{project_dir}' does not contain a dbt_project.yml — "
                "make sure to point to the project root."
            )
        self._project_dir = path
        return str(path)

    def configure_profile(
        self,
        profile_name: str,
        target_name: str,
        db_type: str,
        db_path: str | None = None,
        host: str | None = None,
        port: int | None = None,
        user: str | None = None,
        password: str | None = None,
        dbname: str | None = None,
        schema: str = "main",
    ) -> str:
        """Write a profiles.yml into the project directory.

        Supports DuckDB and PostgreSQL (Supabase) target types.

        Args:
            profile_name: Profile name — must match the 'profile' key in dbt_project.yml.
            target_name: Target name (e.g. 'dev').
            db_type: 'duckdb' or 'postgres'.
            db_path: Path to the DuckDB .duckdb file (required when db_type='duckdb').
            host: PostgreSQL host (required when db_type='postgres').
            port: PostgreSQL port (default 5432).
            user: PostgreSQL user.
            password: PostgreSQL password.
            dbname: PostgreSQL database name.
            schema: Target schema (default 'main').

        Returns:
            Path to the written profiles.yml file.
        """
        project_dir = self._require_project()

        if db_type == "duckdb":
            if db_path is None:
                raise ValueError("db_path is required for db_type='duckdb'.")
            profile_content = (
                f"{profile_name}:\n"
                f"  target: {target_name}\n"
                f"  outputs:\n"
                f"    {target_name}:\n"
                f"      type: duckdb\n"
                f"      path: {db_path}\n"
                f"      schema: {schema}\n"
            )
        elif db_type == "postgres":
            profile_content = (
                f"{profile_name}:\n"
                f"  target: {target_name}\n"
                f"  outputs:\n"
                f"    {target_name}:\n"
                f"      type: postgres\n"
                f"      host: {host}\n"
                f"      port: {port or 5432}\n"
                f"      user: {user}\n"
                f"      password: {password}\n"
                f"      dbname: {dbname}\n"
                f"      schema: {schema}\n"
            )
        else:
            raise ValueError(f"Unsupported db_type '{db_type}'. Use 'duckdb' or 'postgres'.")

        profiles_path = project_dir / "profiles.yml"
        profiles_path.write_text(profile_content, encoding="utf-8")
        return str(profiles_path)

    def write_model(self, model_name: str, sql: str) -> str:
        """Write a SQL transformation model file to the project's models directory.

        The SQL content is provided by the LLM — this method only handles file I/O.

        Args:
            model_name: Model name without extension (e.g. 'fact_sales').
            sql: SQL SELECT statement that defines the transformation.

        Returns:
            Path of the written .sql file.
        """
        # DEV-44: auto-init default project so write_model works before execute_BI_task
        if self._project_dir is None:
            self.init_project("bi_dwh")
        project_dir = self._require_project()
        models_dir = project_dir / "models"
        models_dir.mkdir(exist_ok=True)
        model_path = models_dir / f"{model_name}.sql"
        model_path.write_text(sql, encoding="utf-8")
        return str(model_path)

    def write_schema(self, schema_name: str, yaml_content: str) -> str:
        """Write a schema.yml (or sources.yml) file to the models directory.

        Used to define sources, tests, and documentation for dbt models.

        Args:
            schema_name: File name without extension (e.g. 'schema', 'sources').
            yaml_content: Full YAML content of the schema file.

        Returns:
            Path of the written .yml file.
        """
        project_dir = self._require_project()
        models_dir = project_dir / "models"
        models_dir.mkdir(exist_ok=True)
        schema_path = models_dir / f"{schema_name}.yml"
        schema_path.write_text(yaml_content, encoding="utf-8")
        return str(schema_path)

    def compile_model(self, model_name: str) -> dict[str, Any]:
        """Compile a specific dbt model (syntax check, Jinja rendering) without running it.

        Args:
            model_name: Model name (without extension).

        Returns:
            Dict with 'returncode', 'stdout', 'stderr'.
        """
        self._require_project()
        result = self._run_dbt(
            "compile",
            "--select", model_name,
            "--profiles-dir", str(self._project_dir.resolve()),
        )
        if result["returncode"] != 0:
            raise RuntimeError(f"dbt compile failed for '{model_name}':\n{result['stderr']}")
        return result

    def run_model(self, model_name: str) -> dict[str, Any]:
        """Execute a specific dbt model (materialise the transformation).

        Args:
            model_name: Model name (without extension).  Use '+model_name' to
                        also run upstream models.

        Returns:
            Dict with 'returncode', 'stdout', 'stderr'.

        Raises:
            RuntimeError: If dbt run exits with a non-zero return code.
        """
        self._require_project()
        result = self._run_dbt(
            "run",
            "--select", model_name,
            "--profiles-dir", str(self._project_dir.resolve()),
        )
        if result["returncode"] != 0:
            raise RuntimeError(f"dbt run failed for '{model_name}':\n{result['stderr']}\n{result['stdout']}")
        combined = (result["stdout"] + result["stderr"]).lower()
        if "no enabled node" in combined or "does not match any enabled nodes" in combined:
            raise RuntimeError(
                f"dbt found no model named '{model_name}'. "
                "Ensure DbtRunner.write_model was called first to create the SQL file."
            )
        return result

    def run_tests(self, model_name: str | None = None) -> dict[str, Any]:
        """Run dbt tests for a model (or all models if model_name is None).

        Args:
            model_name: Model name to test.  Pass None to run all tests.

        Returns:
            Dict with 'returncode', 'stdout', 'stderr'.
        """
        self._require_project()
        args = ["test", "--profiles-dir", str(self._project_dir)]
        if model_name:
            args.extend(["--select", model_name])
        result = self._run_dbt(*args)
        return result

    def get_results(self, run_id: str | None = None) -> list[dict[str, Any]]:
        """Read the latest dbt run_results.json and return structured result rows.

        dbt writes run_results.json to the 'target/' directory after every run.

        Args:
            run_id: Reserved for future use (dbt Core does not expose run IDs;
                    this always returns the latest results file).

        Returns:
            List of result dicts (one per model/test node), each with:
            'node_id', 'status', 'execution_time', 'message'.
        """
        project_dir = self._require_project()
        results_path = project_dir / "target" / "run_results.json"
        if not results_path.exists():
            return []

        raw = json.loads(results_path.read_text(encoding="utf-8"))
        results = []
        for r in raw.get("results", []):
            results.append(
                {
                    "node_id": r.get("unique_id", ""),
                    "status": r.get("status", ""),
                    "execution_time": r.get("execution_time", 0),
                    "message": r.get("message", ""),
                }
            )
        return results
