from enum import Enum


class BITaskType(str, Enum):
    INSTANTIATION = "INSTANTIATION"
    CONNECTION_SETUP = "CONNECTION_SETUP"
    CREDENTIAL_REQUEST = "CREDENTIAL_REQUEST"
    SCHEMA_CREATION = "SCHEMA_CREATION"
    DATA_INGESTION = "DATA_INGESTION"
    TRANSFORMATION = "TRANSFORMATION"
